#!/bin/bash
declare a=(100 200 400 800)
declare cores=(1 2 4 6 8 10)

(cd ../src && make clean)
(cd ../src && make all)

rm ../output/timings.txt
rm ../output/mat.txt 
for s in "${a[@]}"
do
    echo SIZE="$s" >&1 | tee -a ../output/timings.txt
    echo >&1 | tee -a ../output/timings.txt
    for c in "${cores[@]}"
    do
        echo core="$c" >&1 | tee -a ../output/timings.txt
        for i in {1..5}
        do
            mpiexec -n "$c" ../src/main "$s" "$s" "$s" >&1 | tee -a ../output/timings.txt
            rm ../output/mat.txt 
        done
        echo >&1 | tee -a ../output/timings.txt
    done
    echo "---" >&1 | tee -a ../output/timings.txt
    echo >&1 | tee -a ../output/timings.txt
done

python3 ../output/timer.py
