#!/bin/bash
declare -A a=(100 200 400 800 1600 3200)
declare -A cores=(1 2 4 8 10)

rm ../output/timings.txt
rm ../output/mat.txt 
(cd ../src && make clean)
(cd ../src && make all)
for s in "${a[@]}"
do
    echo SIZE="$s" >> ../output/timings.txt
    echo >> ../output/timings.txt
    for c in "${cores[@]}"
    do
        echo core="$c" >> ../output/timings.txt
        for i in {1..5}
        do
            mpiexec -n "$c" ../src/main "$s" "$s" "$s" >> ../output/timings.txt
            rm ../output/mat.txt 
        done
        echo >> ../output/timings.txt
    done
    echo >> ../output/timings.txt
done
python3 ../output/checker.py
